<?php
// ============================================================
// BOJLER SZERELŐ BUDAPEST – KERÜLETI ALOLDALAK SABLON
// Provi Domus Kft. | bojler-szerelo-budapest.hu
// ============================================================

$phone      = '06 (70) 164-4000';
$phone_link = 'tel:+36701644000';
$wa_link    = 'https://wa.me/36701644000?text=Szia!+%C3%89rdekl%C5%91dn%C3%A9k+a+bojler+szerel%C3%A9s+ir%C3%A1nt.';
$viber_link = 'viber://chat?number=%2B36701644000';
$email      = 'providomuszkft@gmail.com';
$base       = 'https://www.bojler-szerelo-budapest.hu';

// ============================================================
// 23 KERÜLET EGYEDI ADATAI – NEM DUPLIKÁLT TARTALOM
// ============================================================
$keruletek = [

  1 => [
    'nev'        => 'I. kerület',
    'roman'      => 'I.',
    'reszek'     => 'Belváros, Lipótváros, Vár, Tabán, Víziváros, Krisztinaváros',
    'jellemzo'   => 'Az I. kerületben sok régi, műemléki épület található – a vízvezetékek és bojlerek átlagos kora itt 30-50 év. A kazánházas rendszerekről egyéni bojlerre való áttérés is gyakori feladat.',
    'hero_h1'    => 'Bojler Szerelő Budapest I. Kerület – Belváros, Vár, Víziváros',
    'hero_sub'   => 'Villanybojler javítás, csere és vízkőtelenítés a budapesti I. kerületben – Belváros, Tabán, Krisztinaváros területén. 1-2 óra kiszállás, 0-24.',
    'ai_text'    => 'Az I. kerületi bojler javítás jellemzően régi, 30-50 éves épületek műemlékileg védett lakásaiban zajlik. A Provi Domus Kft. szerelesői ismerik a Vár, a Belváros és a Víziváros épületeinek sajátosságait – szűk tereket, régi csöveket, beépített bojlereket. Kiszállás: 1-2 óra, munkadíj: 10.000–28.000 Ft.',
    'problema'   => 'Az I. kerületi régi épületek bojlerei gyakran meszesek és elöregedtek. A műemléki épületekben szűk helyeken, beépített fülkékben dolgozunk – erre specializálódtunk.',
    'testimonial_nev'    => 'Fekete Ágnes',
    'testimonial_szoveg' => 'Várnegyedi lakásunkban volt a bojler probléma – szűk fürdőszobában, régi beépítés. Más szerelő nem merte vállalni. Provi Domus 3 óra alatt megoldotta.',
    'testimonial_ker'    => 'Budapest I. kerület – Várnegyed',
    'faq_q'      => 'Vállalnak bojler szerelést a budapesti I. kerületben, műemléki épületekben is?',
    'faq_a'      => 'Igen, az I. kerületben – Belváros, Vár, Tabán, Víziváros területén – rendszeresen dolgozunk. Műemléki épületek szűk tereit, beépített bojler fülkéit is kezeljük. Kiszállás: 1-2 óra.',
    'szomszed'   => [2, 5, 11, 12],
  ],

  2 => [
    'nev'        => 'II. kerület',
    'roman'      => 'II.',
    'reszek'     => 'Rózsadomb, Pesthidegkút, Pasarét, Törökvész, Hűvösvölgy, Budakeszi út',
    'jellemzo'   => 'A II. kerület prémium budai lakónegyed – sok nagy alapterületű, 80-200 literes bojlerrel felszerelt ingatlan. A Rózsadomb villáiban és a Pasarét társasházaiban egyaránt dolgozunk.',
    'hero_h1'    => 'Bojler Szerelő Budapest II. Kerület – Rózsadomb, Pasarét, Hűvösvölgy',
    'hero_sub'   => 'Villanybojler javítás, csere és vízkőtelenítés a II. kerületben – Rózsadomb, Pesthidegkút, Törökvész, Hűvösvölgy területén. 1-2 óra kiszállás, 0-24.',
    'ai_text'    => 'A II. kerületi bojler szerelés jellemzően nagyobb kapacitású (100-200 literes) készülékeket érint. A Rózsadombon és Pasaréten található villák és prémium lakások bojlereinél Ariston és Hajdú márkák dominálnak. Provi Domus Kft. – kiszállás 1-2 óra, munkadíj: 10.000–35.000 Ft.',
    'problema'   => 'A II. kerületi nagyobb ingatlanokban 150-200 literes bojlerek üzemelnek – ezek cseréje speciális felszerelést igényel. Nagy és nehéz készülékek mozgatásában is tapasztaltak vagyunk.',
    'testimonial_nev'    => 'Balogh Tamás',
    'testimonial_szoveg' => 'Rózsadombi házunkban 200 literes Hajdú bojlert cseréltünk. Ketten jöttek, gyorsan és profin végezték. A régit elvitték, az újat pontosan bekötötték.',
    'testimonial_ker'    => 'Budapest II. kerület – Rózsadomb',
    'faq_q'      => 'Nagy kapacitású, 150-200 literes bojlert is cserélnek a II. kerületben?',
    'faq_a'      => 'Igen, a II. kerületben – Rózsadomb, Pasarét, Hűvösvölgy területén – nagy kapacitású bojlereket is cserélünk. Két szerelő érkezik, a régi készüléket elszállítjuk. Kiszállás: 1-2 óra.',
    'szomszed'   => [1, 3, 12],
  ],

  3 => [
    'nev'        => 'III. kerület',
    'roman'      => 'III.',
    'reszek'     => 'Óbuda, Békásmegyer, Csillaghegy, Pünkösdfürdő, Aquincum, Solymárvölgy',
    'jellemzo'   => 'A III. kerület Óbuda ipari múlttal rendelkező, de mára lakónegyeddé vált városrész. A Békásmegyeri panelházak és az óbudai társasházak bojlerjei eltérő kihívásokat jelentenek.',
    'hero_h1'    => 'Bojler Szerelő Budapest III. Kerület – Óbuda, Békásmegyer, Csillaghegy',
    'hero_sub'   => 'Villanybojler javítás, csere Óbudán, Békásmegyeren és Csillaghegyen – 1-2 óra kiszállás, 0-24, garancia.',
    'ai_text'    => 'A III. kerületben – Óbuda, Békásmegyer, Csillaghegy – sok panel lakásban és régi társasházban dolgozunk. A panelos bojler csere egyszerűbb, az óbudai régi épületeké több szaktudást igényel. Provi Domus Kft. kiszállás 1-2 óra, munkadíj: 10.000–35.000 Ft.',
    'problema'   => 'Békásmegyeren és Óbudán sok a 20-30 éves elöregedett bojler. A panel lakásokban kis helyiségekben dolgozunk – erre specializálódtunk.',
    'testimonial_nev'    => 'Varga Zoltán',
    'testimonial_szoveg' => 'Békásmegyeri panellakásban cseréltük az elromlott bojlert. Gyorsan jöttek, a szűk fürdőben is ügyesen dolgoztak. Korrekt áron, garancia papírral.',
    'testimonial_ker'    => 'Budapest III. kerület – Békásmegyer',
    'faq_q'      => 'Panel lakásban is vállalnak bojler cserét a III. kerületben?',
    'faq_a'      => 'Igen, a III. kerületben – Óbuda, Békásmegyer, Csillaghegy – panel és tégla épületekben egyaránt dolgozunk. Szűk fürdőszobákban is tapasztaltak vagyunk. Kiszállás: 1-2 óra.',
    'szomszed'   => [2, 4, 13],
  ],

  4 => [
    'nev'        => 'IV. kerület',
    'roman'      => 'IV.',
    'reszek'     => 'Újpest, Káposztásmegyer, Újpesti rakpart',
    'jellemzo'   => 'Az IV. kerület Újpest iparvárosból lakóvárossá vált. A Káposztásmegyeri lakótelepen sok panel és a régi Újpest tégla épületeiben egyaránt javítunk.',
    'hero_h1'    => 'Bojler Szerelő Budapest IV. Kerület – Újpest, Káposztásmegyer',
    'hero_sub'   => 'Villanybojler javítás, csere és vízkőtelenítés Újpesten és Káposztásmegyeren – 1-2 óra kiszállás, 0-24, garancia.',
    'ai_text'    => 'A IV. kerületi – Újpest, Káposztásmegyer – bojler javítás és csere esetén a Provi Domus Kft. szerelesői 1-2 órán belül megérkeznek. Munkadíj: 10.000–35.000 Ft. Ariston és Hajdú szakszerviz.',
    'problema'   => 'Újpesten és Káposztásmegyeren sok a kazánházi rendszerről egyéni bojlerre átálló lakás. Az átállást és az egyedi bekötést is vállaljuk.',
    'testimonial_nev'    => 'Kovács László',
    'testimonial_szoveg' => 'Újpesti lakásomban nem melegített a bojler. Reggel hívtam őket, délre már volt meleg víz. Termosztát csere volt, 14.000 Ft. Korrekt.',
    'testimonial_ker'    => 'Budapest IV. kerület – Újpest',
    'faq_q'      => 'Vállalnak bojler javítást a IV. kerületben, Újpesten?',
    'faq_a'      => 'Igen, a IV. kerületben – Újpest, Káposztásmegyer – rendszeresen dolgozunk. Kiszállás 1-2 óra, 0-24-ben, hétvégén is.',
    'szomszed'   => [3, 13, 15],
  ],

  5 => [
    'nev'        => 'V. kerület',
    'roman'      => 'V.',
    'reszek'     => 'Belváros, Lipótváros, Parlament negyed, Bajcsy-Zsilinszky út',
    'jellemzo'   => 'Az V. kerület Budapest szíve – irodaházak, bankok, de sok lakás is van. A bérházak és szállodák bojlerei egyaránt feladatot adnak. Gyors kiszállás a belvárosba garantált.',
    'hero_h1'    => 'Bojler Szerelő Budapest V. Kerület – Belváros, Lipótváros, Parlament',
    'hero_sub'   => 'Villanybojler javítás és csere a budapesti V. kerületben – Belváros, Lipótváros, Parlament negyed. Gyors, 1 órás kiszállás, 0-24.',
    'ai_text'    => 'Az V. kerületi – Belváros, Lipótváros – bojler szereléshez a Provi Domus Kft. 1 órán belül megérkezik. A belvárosi bérházak és társasházak bojlereit kezeljük. Munkadíj: 10.000–35.000 Ft.',
    'problema'   => 'Az V. kerületi régi bérházakban sok a szűk, beépített fürdőszoba – ott is megoldjuk a javítást vagy cserét. A belvárosba a leggyorsabb kiszállást garantáljuk.',
    'testimonial_nev'    => 'Halász Péter',
    'testimonial_szoveg' => 'Lipótvárosban volt a gond, 9-kor hívtam, 10:30-ra ott voltak. Fűtőszál csere, 16.000 Ft. Gyors és megbízható.',
    'testimonial_ker'    => 'Budapest V. kerület – Lipótváros',
    'faq_q'      => 'Vállalnak bojler javítást az V. kerületben, a Belvárosban?',
    'faq_a'      => 'Igen, az V. kerületbe – Belváros, Lipótváros – 1 órán belül kiszállunk. A belvárosi régi bérházak szűk fürdőszobáiban is tapasztaltak vagyunk. 0-24.',
    'szomszed'   => [1, 6, 7, 9],
  ],

  6 => [
    'nev'        => 'VI. kerület',
    'roman'      => 'VI.',
    'reszek'     => 'Terézváros, Andrássy út, Városliget, Oktogon, Nyugati',
    'jellemzo'   => 'A VI. kerület elegáns pesti bérházai sokszor 100+ éves épületek – ezekben régi csőrendszerek és bojlerek vannak. Az Andrássy út mentén és a Terézvárosban egyaránt dolgozunk.',
    'hero_h1'    => 'Bojler Szerelő Budapest VI. Kerület – Terézváros, Andrássy út, Oktogon',
    'hero_sub'   => 'Villanybojler javítás és csere a VI. kerületben – Terézváros, Andrássy út, Oktogon, Nyugati. 1-2 óra kiszállás, 0-24, garancia.',
    'ai_text'    => 'A VI. kerületi – Terézváros – bojler javítás esetén a Provi Domus Kft. 1-2 órán belül kiszáll. A régi pesti bérházak elöregedett bojlerjeit és csőrendszereit kezeljük. Munkadíj: 10.000–35.000 Ft.',
    'problema'   => 'A VI. kerületi százéves bérházakban a víz meszes – ez felgyorsítja a bojlerek elhasználódását. Az V. és VI. kerületbe a leggyorsabb kiszállást garantáljuk.',
    'testimonial_nev'    => 'Tóth Mária',
    'testimonial_szoveg' => 'Terézvárosban, régi bérházban cseréltük a 18 éves bojlert. Pontosan jöttek, profi munkát végeztek, a régit elvitték. Ajánlom.',
    'testimonial_ker'    => 'Budapest VI. kerület – Terézváros',
    'faq_q'      => 'Vállalnak bojler cserét a VI. kerületben, régi pesti bérházban is?',
    'faq_a'      => 'Igen, a VI. kerületben – Terézváros, Andrássy út – régi bérházakban is dolgozunk. A szűk tereket és régi csőrendszereket kezeljük. Kiszállás 1-2 óra.',
    'szomszed'   => [5, 7, 13, 14],
  ],

  7 => [
    'nev'        => 'VII. kerület',
    'roman'      => 'VII.',
    'reszek'     => 'Erzsébetváros, Klauzál tér, Dohány utca, Rákóczi út, Nagydiófa utca',
    'jellemzo'   => 'A VII. kerület – Budapest zsidónegyede – tele van felújított és felújítatlan bérházakkal. A turisztikai rész és a csendes lakónegyedek eltérő bojler igényeket mutatnak.',
    'hero_h1'    => 'Bojler Szerelő Budapest VII. Kerület – Erzsébetváros, Klauzál tér',
    'hero_sub'   => 'Villanybojler javítás, csere Erzsébetvárosban – Klauzál tér, Dohány utca, Rákóczi út. 1-2 óra kiszállás, 0-24.',
    'ai_text'    => 'A VII. kerületi – Erzsébetváros – bojler javítás esetén a Provi Domus Kft. 1-2 óra kiszállással dolgozik. A felújított és eredeti állapotú bérházakban egyaránt tapasztaltak vagyunk. Munkadíj: 10.000–35.000 Ft.',
    'problema'   => 'Erzsébetvárosban sok az Airbnb-vé alakított lakás ahol a bojler intenzívebb terhelésnek van kitéve. Gyors, megbízható javítást vállalunk bérbe adott ingatlanokba is.',
    'testimonial_nev'    => 'Gál Norbert',
    'testimonial_szoveg' => 'Klauzál téri bérleménybe hívtam őket – a bérlő reggel jelezte hogy nincs meleg víz. Délelőtt megoldva. Profik.',
    'testimonial_ker'    => 'Budapest VII. kerület – Erzsébetváros',
    'faq_q'      => 'Vállalnak sürgős bojler javítást a VII. kerületben, bérlemény esetén is?',
    'faq_a'      => 'Igen, a VII. kerületben – Erzsébetváros – bérbeadott lakásokba is kiszállunk. Gyors, 1-2 órás kiszállás, 0-24-ben. A bérlő és a tulajdonos is hívhat minket.',
    'szomszed'   => [6, 8, 14],
  ],

  8 => [
    'nev'        => 'VIII. kerület',
    'roman'      => 'VIII.',
    'reszek'     => 'Józsefváros, Corvin negyed, Palotanegyed, Tisztviselőtelep, Magdolnaváros',
    'jellemzo'   => 'A VIII. kerület megújuló városnegyed – a Corvin negyed modern lakásai és a Palotanegyed felújított bérházai eltérő bojler igényeket mutatnak.',
    'hero_h1'    => 'Bojler Szerelő Budapest VIII. Kerület – Józsefváros, Corvin, Palotanegyed',
    'hero_sub'   => 'Villanybojler javítás, csere Józsefvárosban – Corvin negyed, Palotanegyed, Tisztviselőtelep. 1-2 óra kiszállás, 0-24.',
    'ai_text'    => 'A VIII. kerületi – Józsefváros, Corvin negyed – bojler javítás esetén a Provi Domus Kft. 1-2 óra alatt kiszáll. Modern és régi épületekben egyaránt dolgozunk. Munkadíj: 10.000–35.000 Ft.',
    'problema'   => 'A Corvin negyedben sok az új beépítésű Ariston és Bosch bojler – ezek szervizét vállaljuk. A Palotanegyedben régebbi készülékek dominálnak.',
    'testimonial_nev'    => 'Szabó Réka',
    'testimonial_szoveg' => 'Corvin negyedben, új lakásunkban az Ariston bojler nem melegített. Kiszálltak, biztonsági hőkapcsoló volt – 20 perc és kész. Korrekt.',
    'testimonial_ker'    => 'Budapest VIII. kerület – Corvin negyed',
    'faq_q'      => 'Ariston bojler javítást vállalnak a VIII. kerületben?',
    'faq_a'      => 'Igen, a VIII. kerületben – Józsefváros, Corvin negyed – Ariston, Hajdú, Bosch bojlereket is javítunk. Kiszállás 1-2 óra, 0-24.',
    'szomszed'   => [7, 9, 14],
  ],

  9 => [
    'nev'        => 'IX. kerület',
    'roman'      => 'IX.',
    'reszek'     => 'Ferencváros, Millenniumi negyed, Soroksári út, Közvágóhíd, Középső-Ferencváros',
    'jellemzo'   => 'A IX. kerület gyorsan fejlődő városrész – a Millenniumi negyed új lakásai és a régi Ferencváros bérházai vegyes képet mutatnak. Mindkét típusú épületben dolgozunk.',
    'hero_h1'    => 'Bojler Szerelő Budapest IX. Kerület – Ferencváros, Millenniumi Negyed',
    'hero_sub'   => 'Villanybojler javítás, csere a IX. kerületben – Ferencváros, Millenniumi negyed, Soroksári út. 1-2 óra kiszállás, 0-24.',
    'ai_text'    => 'A IX. kerületi – Ferencváros – bojler javítás esetén a Provi Domus Kft. 1-2 óra kiszállással dolgozik. A Millenniumi negyed új és a régi Ferencváros bérház bojlerjeit egyaránt kezeljük. Munkadíj: 10.000–35.000 Ft.',
    'problema'   => 'Ferencvárosban sok az újonnan beköltöző bérlő – a bojler problémát gyorsan kell megoldani. Garantált kiszállási idő, 0-24.',
    'testimonial_nev'    => 'Papp Ildikó',
    'testimonial_szoveg' => 'Ferencvárosban, Bosch bojler nem melegített. Vasárnap hívtam őket, megérkeztek és megjavították. Hétvégén is vállalnak, ez nagyon fontos volt.',
    'testimonial_ker'    => 'Budapest IX. kerület – Ferencváros',
    'faq_q'      => 'Vállalnak hétvégi bojler javítást a IX. kerületben?',
    'faq_a'      => 'Igen, a IX. kerületben – Ferencváros – hétvégén és ünnepnapokon is kiszállunk, 0-24-ben. Sürgősségi díj hétvégén érvényes.',
    'szomszed'   => [5, 8, 20],
  ],

  10 => [
    'nev'        => 'X. kerület',
    'roman'      => 'X.',
    'reszek'     => 'Kőbánya, Óhegy, Újhegy, Biksad, Mádi utca negyed',
    'jellemzo'   => 'A X. kerület ipari múltú, mára vegyes funkcióú városrész. A Kőbányai panel és téglaépületek bojlerei rendszeres karbantartást igényelnek.',
    'hero_h1'    => 'Bojler Szerelő Budapest X. Kerület – Kőbánya, Óhegy, Újhegy',
    'hero_sub'   => 'Villanybojler javítás, csere Kőbányán – Óhegy, Újhegy, Biksad negyed. 1-2 óra kiszállás, 0-24.',
    'ai_text'    => 'A X. kerületi – Kőbánya – bojler javítás esetén a Provi Domus Kft. 1-2 óra kiszállással dolgozik. Panel és téglaépületek bojlerjeit egyaránt kezeljük. Munkadíj: 10.000–35.000 Ft.',
    'problema'   => 'Kőbányán sok az elöregedett, 15-20 éves bojler a panelházakban. Vízkőtelenítéssel akár 5 évvel meg lehet hosszabbítani az élettartamot.',
    'testimonial_nev'    => 'Horváth Béla',
    'testimonial_szoveg' => 'Kőbányai panellakásban 20 éves Hajdú bojler volt. Azt mondták megéri vízkőteleníteni cseréje helyett. Megtakarítottam 30.000 forintot.',
    'testimonial_ker'    => 'Budapest X. kerület – Kőbánya',
    'faq_q'      => 'Érdemes vízkőteleníteni a X. kerületben, vagy inkább cserélni a bojlert?',
    'faq_a'      => 'Ha a bojler 12 évnél fiatalabb és a tartály ép, vízkőtelenítéssel olcsóbban megúszható. A X. kerületben – Kőbánya – telefonon segítünk eldönteni, ingyenesen.',
    'szomszed'   => [9, 17, 19],
  ],

  11 => [
    'nev'        => 'XI. kerület',
    'roman'      => 'XI.',
    'reszek'     => 'Újbuda, Kelenföld, Lágymányos, Gazdagrét, Sasad, Albertfalva, Kelenföldi lakótelep',
    'jellemzo'   => 'A XI. kerület Budapest egyik legnagyobb kerülete – a Lágymányosi modern lakópark, a Gazdagrét panelei és a Sasad prémiuma egyaránt feladatot ad. Minden területen ismertek vagyunk.',
    'hero_h1'    => 'Bojler Szerelő Budapest XI. Kerület – Újbuda, Kelenföld, Gazdagrét',
    'hero_sub'   => 'Villanybojler javítás, csere a XI. kerületben – Újbuda, Kelenföld, Lágymányos, Gazdagrét. 1-2 óra kiszállás, 0-24, garancia.',
    'ai_text'    => 'A XI. kerületi – Újbuda, Kelenföld – bojler javítás esetén a Provi Domus Kft. 1-2 óra kiszállással dolgozik. A Kelenföldi lakótelep panel és a Gazdagrét ház típusú épületek bojlerjeit egyaránt kezeljük. Munkadíj: 10.000–35.000 Ft.',
    'problema'   => 'A XI. kerület nagy területén belül is gyors kiszállást garantálunk – Albertfalvától Sasadig, Kelenföldig. Ismerjük a kerület minden részét.',
    'testimonial_nev'    => 'Kiss Éva',
    'testimonial_szoveg' => 'Gazdaréti lakásunkban az Ariston bojler leverte a biztosítékot. Délután 5-kor hívtam, este 7-re megjavítva. Fűtőszál csere volt, gyors és korrekt.',
    'testimonial_ker'    => 'Budapest XI. kerület – Gazdagrét',
    'faq_q'      => 'Vállalnak bojler javítást Gazdaréten, Sasadon és a XI. kerület távolabbi részeiben is?',
    'faq_a'      => 'Igen, a teljes XI. kerületben – Kelenföld, Gazdagrét, Sasad, Albertfalva, Lágymányos – kiszállunk. 1-2 óra a kiszállási idő a kerület bármely pontjára.',
    'szomszed'   => [1, 12, 22],
  ],

  12 => [
    'nev'        => 'XII. kerület',
    'roman'      => 'XII.',
    'reszek'     => 'Hegyvidék, Németvölgy, Orbánhegy, Svábhegy, Mártonhegy, Zugliget, Normafa',
    'jellemzo'   => 'A XII. kerület prémium budai hegyvidéki terület – sok villa és igényes társasház. Az Ariston prémium és Hajdú nagy kapacitású típusok dominálnak.',
    'hero_h1'    => 'Bojler Szerelő Budapest XII. Kerület – Hegyvidék, Svábhegy, Zugliget',
    'hero_sub'   => 'Villanybojler javítás, csere a XII. kerületben – Hegyvidék, Svábhegy, Orbánhegy, Zugliget. 1-2 óra kiszállás, 0-24.',
    'ai_text'    => 'A XII. kerületi – Hegyvidék, Svábhegy – bojler javítás esetén a Provi Domus Kft. 1-2 óra kiszállással dolgozik. A budai villákban és igényes társasházakban elsősorban Ariston és Hajdú prémium típusokat szereljük. Munkadíj: 10.000–35.000 Ft.',
    'problema'   => 'A XII. kerületi prémium ingatlanokban elvárás a precíz, rendezett munka. Minden esetben takarítva hagyjuk el a helyszínt, és prémium alkatrészeket használunk.',
    'testimonial_nev'    => 'Dr. Nagy Péter',
    'testimonial_szoveg' => 'Svábhegyi házunkban Ariston Lydos bojler cserére volt szükség. Pontosak, precízek, a helyszínt tökéletesen hagyták el. Eredeti Ariston alkatrészek, garancia.',
    'testimonial_ker'    => 'Budapest XII. kerület – Svábhegy',
    'faq_q'      => 'Prémium, nagy kapacitású bojlereket is szerelnek a XII. kerületben?',
    'faq_a'      => 'Igen, a XII. kerületben – Hegyvidék, Svábhegy, Zugliget – prémium Ariston és Hajdú típusokat is szervizeljük. Eredeti alkatrészek, garancia. Kiszállás 1-2 óra.',
    'szomszed'   => [1, 2, 11],
  ],

  13 => [
    'nev'        => 'XIII. kerület',
    'roman'      => 'XIII.',
    'reszek'     => 'Angyalföld, Újlipótváros, Vizafogó, Göncz Árpád városközpont, Dráva utca',
    'jellemzo'   => 'A XIII. kerület vegyes képet mutat – az Újlipótváros elegáns bérházai és az Angyalföld panel lakótelep eltérő bojler igényeket mutatnak. Mindkét területen tapasztaltak vagyunk.',
    'hero_h1'    => 'Bojler Szerelő Budapest XIII. Kerület – Angyalföld, Újlipótváros',
    'hero_sub'   => 'Villanybojler javítás, csere a XIII. kerületben – Angyalföld, Újlipótváros, Vizafogó, Göncz Árpád. 1-2 óra kiszállás, 0-24.',
    'ai_text'    => 'A XIII. kerületi – Angyalföld, Újlipótváros – bojler javítás esetén a Provi Domus Kft. 1-2 óra kiszállással dolgozik. Panel és tégla épületekben egyaránt tapasztaltak vagyunk. Munkadíj: 10.000–35.000 Ft.',
    'problema'   => 'Az Angyalföldi panel lakásokban sok az elöregedett, 15+ éves bojler. Az Újlipótvárosban felújított lakások modern Ariston és Bosch bojlerek szervizét igénylik.',
    'testimonial_nev'    => 'Farkas Judit',
    'testimonial_szoveg' => 'Újlipótvárosban, felújított lakásban a 3 éves Ariston Velis nem melegített. Garancián belül is bevállalták, gyorsan megoldottak. Profi csapat.',
    'testimonial_ker'    => 'Budapest XIII. kerület – Újlipótváros',
    'faq_q'      => 'Vállalnak bojler javítást a XIII. kerületben, Újlipótvárosban és Angyalföldön is?',
    'faq_a'      => 'Igen, a XIII. kerület teljes területén – Angyalföld, Újlipótváros, Vizafogó – kiszállunk. 1-2 óra, 0-24.',
    'szomszed'   => [3, 4, 6, 14],
  ],

  14 => [
    'nev'        => 'XIV. kerület',
    'roman'      => 'XIV.',
    'reszek'     => 'Zugló, Rákosfalva, Istvánmező, Herminamező, Törökőr, Alsórákos',
    'jellemzo'   => 'A XIV. kerület Zugló Budapest egyik legnépszerűbb lakóhelye – csendes utcák, zöld környezet, sok társasház és ház. A Zuglói bojlerek átlagosan 10-20 éves korúak.',
    'hero_h1'    => 'Bojler Szerelő Budapest XIV. Kerület – Zugló, Rákosfalva, Herminamező',
    'hero_sub'   => 'Villanybojler javítás, csere Zuglóban – Rákosfalva, Istvánmező, Herminamező, Törökőr. 1-2 óra kiszállás, 0-24.',
    'ai_text'    => 'A XIV. kerületi – Zugló – bojler javítás esetén a Provi Domus Kft. 1-2 óra kiszállással dolgozik. A Zuglói társasházak és kertes házak bojlerjeit egyaránt kezeljük. Munkadíj: 10.000–35.000 Ft.',
    'problema'   => 'Zuglóban sok a 10-15 éves bojler, amelyek már kezdenek elöregedni. A megelőző vízkőtelenítés évente elvégezve 3-5 évvel meghosszabbíthatja az élettartamot.',
    'testimonial_nev'    => 'Mészáros Gábor',
    'testimonial_szoveg' => 'Zuglóban, Törökőrön korog és lassan melegített a bojler. Vízkőtelenítés és anódrúd csere volt. 3 évvel meghosszabbította az élettartamot. Megérte.',
    'testimonial_ker'    => 'Budapest XIV. kerület – Zugló',
    'faq_q'      => 'Mennyibe kerül a bojler vízkőtelenítés a XIV. kerületben, Zuglóban?',
    'faq_a'      => 'A bojler vízkőtelenítés és anódrúd csere munkadíja 12.000–20.000 Ft a XIV. kerületben – Zugló. Az alkatrész ára külön. Kiszállás 1-2 óra.',
    'szomszed'   => [6, 7, 13, 16],
  ],

  15 => [
    'nev'        => 'XV. kerület',
    'roman'      => 'XV.',
    'reszek'     => 'Rákospalota, Pestújhely, Újpalota, Rákospalotai lakótelep',
    'jellemzo'   => 'A XV. kerület észak-pesti lakónegyed – a Rákospalotai lakótelep nagy panelei és az Újpalota kertes házas részei eltérő igényeket mutatnak.',
    'hero_h1'    => 'Bojler Szerelő Budapest XV. Kerület – Rákospalota, Pestújhely, Újpalota',
    'hero_sub'   => 'Villanybojler javítás, csere a XV. kerületben – Rákospalota, Pestújhely, Újpalota. 1-2 óra kiszállás, 0-24.',
    'ai_text'    => 'A XV. kerületi – Rákospalota, Pestújhely – bojler javítás esetén a Provi Domus Kft. 1-2 óra kiszállással dolgozik. Panel lakások és kertes házak bojlerjeit egyaránt kezeljük. Munkadíj: 10.000–35.000 Ft.',
    'problema'   => 'A XV. kerületi panelházakban sok a 20+ éves elöregedett bojler, amelyek cseréje időszerű. A csere és az elszállítás is egy látogatás alatt elvégezhető.',
    'testimonial_nev'    => 'Pintér Anna',
    'testimonial_szoveg' => 'Rákospalotán 22 éves bojlert cseréltünk. Pontosak, gyorsak, a régit elvitték, az új másnap már melegített. Jó áron.',
    'testimonial_ker'    => 'Budapest XV. kerület – Rákospalota',
    'faq_q'      => 'Vállalnak bojler cserét Rákospalotán, a XV. kerületben?',
    'faq_a'      => 'Igen, a XV. kerületben – Rákospalota, Pestújhely, Újpalota – bojler cserét és javítást is vállalunk. Kiszállás 1-2 óra, 0-24.',
    'szomszed'   => [4, 13, 16],
  ],

  16 => [
    'nev'        => 'XVI. kerület',
    'roman'      => 'XVI.',
    'reszek'     => 'Mátyásföld, Sashalom, Cinkota, Árpádföld, Rákosszentmihály',
    'jellemzo'   => 'A XVI. kerület csendes, kertvárosi jellegű Budapest keleti részén. Sok a régebbi, kertes ház, ahol nagyobb kapacitású bojlerek üzemelnek.',
    'hero_h1'    => 'Bojler Szerelő Budapest XVI. Kerület – Mátyásföld, Sashalom, Cinkota',
    'hero_sub'   => 'Villanybojler javítás, csere a XVI. kerületben – Mátyásföld, Sashalom, Cinkota, Rákosszentmihály. 1-2 óra kiszállás, 0-24.',
    'ai_text'    => 'A XVI. kerületi – Mátyásföld, Sashalom – bojler javítás esetén a Provi Domus Kft. 1-2 óra kiszállással dolgozik. Kertes házak nagy kapacitású bojlerjeit is kezeljük. Munkadíj: 10.000–35.000 Ft.',
    'problema'   => 'A XVI. kerületi kertes házakban 150-200 literes Hajdú bojlerek üzemelnek. A nagy kapacitású készülékek cseréjéhez két szerelő érkezik.',
    'testimonial_nev'    => 'Lukács Tibor',
    'testimonial_szoveg' => 'Sashalmi házunkban 150 literes Hajdú bojlert cseréltünk. Ketten jöttek, profi munka, a régit elvitték. Elégedett vagyok.',
    'testimonial_ker'    => 'Budapest XVI. kerület – Sashalom',
    'faq_q'      => 'Nagy kapacitású, 150 literes bojlert is cserélnek a XVI. kerületben?',
    'faq_a'      => 'Igen, a XVI. kerületben – Mátyásföld, Sashalom, Cinkota – nagy bojlereket is cserélünk. Két szerelő érkezik, a régit elszállítjuk. Kiszállás 1-2 óra.',
    'szomszed'   => [14, 15, 17],
  ],

  17 => [
    'nev'        => 'XVII. kerület',
    'roman'      => 'XVII.',
    'reszek'     => 'Rákosmente, Rákoskeresztúr, Rákoscsaba, Rákoshegy, Rákosliget',
    'jellemzo'   => 'A XVII. kerület Budapest keleti kertvárosa – sok a régebbi, önálló ház ahol a bojler az egyetlen melegvíz forrás. A meghibásodás azonnali beavatkozást igényel.',
    'hero_h1'    => 'Bojler Szerelő Budapest XVII. Kerület – Rákosmente, Rákoskeresztúr, Rákoscsaba',
    'hero_sub'   => 'Villanybojler javítás, csere a XVII. kerületben – Rákosmente, Rákoskeresztúr, Rákoscsaba, Rákoshegy. 1-2 óra kiszállás, 0-24.',
    'ai_text'    => 'A XVII. kerületi – Rákosmente – bojler javítás esetén a Provi Domus Kft. 1-2 óra kiszállással dolgozik. Kertes házak és lakótelepek bojlerjeit egyaránt kezeljük. Munkadíj: 10.000–35.000 Ft.',
    'problema'   => 'Rákosmentén sok a régi, 15-20 éves bojler. Az egész háztartás meleg vize a bojlertől függ – ezért a gyors kiszállás kritikus.',
    'testimonial_nev'    => 'Bíró István',
    'testimonial_szoveg' => 'Rákoskeresztúri házunkban télen romlott el a bojler. Estére kiszálltak, fűtőszálat cseréltek. Télre nem maradtunk meleg víz nélkül. Hálás vagyok.',
    'testimonial_ker'    => 'Budapest XVII. kerület – Rákoskeresztúr',
    'faq_q'      => 'Vállalnak sürgős bojler javítást a XVII. kerületben, Rákosmentén?',
    'faq_a'      => 'Igen, a XVII. kerületben – Rákosmente, Rákoskeresztúr, Rákoscsaba – 1-2 órán belül kiszállunk. 0-24, hétvégén és ünnepnapokon is.',
    'szomszed'   => [10, 16, 18],
  ],

  18 => [
    'nev'        => 'XVIII. kerület',
    'roman'      => 'XVIII.',
    'reszek'     => 'Pestszentlőrinc, Pestszentimre, Lakótelep, Szemeretelep',
    'jellemzo'   => 'A XVIII. kerület déli pesti városrész – Pestszentlőrinc és Pestszentimre régi társasházai és az újabb panelépületek vegyes képet mutatnak.',
    'hero_h1'    => 'Bojler Szerelő Budapest XVIII. Kerület – Pestszentlőrinc, Pestszentimre',
    'hero_sub'   => 'Villanybojler javítás, csere a XVIII. kerületben – Pestszentlőrinc, Pestszentimre, Lakótelep. 1-2 óra kiszállás, 0-24.',
    'ai_text'    => 'A XVIII. kerületi – Pestszentlőrinc, Pestszentimre – bojler javítás esetén a Provi Domus Kft. 1-2 óra kiszállással dolgozik. Munkadíj: 10.000–35.000 Ft.',
    'problema'   => 'Pestszentlőrincen és Pestszentimrén sok a régi társasházi bojler, amelyek rendszeres karbantartást igényelnek. Éves vízkőtelenítéssel megelőzhető a korai meghibásodás.',
    'testimonial_nev'    => 'Oláh Margit',
    'testimonial_szoveg' => 'Pestszentlőrinci lakásomban évente vízkőteleníttetem a bojlert. Provi Domus mindig pontosan jön, mindig korrekt áron dolgoznak. Ajánlom.',
    'testimonial_ker'    => 'Budapest XVIII. kerület – Pestszentlőrinc',
    'faq_q'      => 'Vállalnak rendszeres bojler karbantartást a XVIII. kerületben?',
    'faq_a'      => 'Igen, a XVIII. kerületben – Pestszentlőrinc, Pestszentimre – éves karbantartást (vízkőtelenítés, anódrúd csere) is vállalunk. Hívjon előre időpontra.',
    'szomszed'   => [17, 19, 20],
  ],

  19 => [
    'nev'        => 'XIX. kerület',
    'roman'      => 'XIX.',
    'reszek'     => 'Kispest, Wekerletelep, Vörösmarty tér',
    'jellemzo'   => 'A XIX. kerület Kispest Budapest egyedi városrészének, a Wekerletelepnek az otthona – védett műemléki területen belüli épületek sajátos kihívásokat jelentenek.',
    'hero_h1'    => 'Bojler Szerelő Budapest XIX. Kerület – Kispest, Wekerletelep',
    'hero_sub'   => 'Villanybojler javítás, csere a XIX. kerületben – Kispest, Wekerletelep, Vörösmarty tér. 1-2 óra kiszállás, 0-24.',
    'ai_text'    => 'A XIX. kerületi – Kispest, Wekerletelep – bojler javítás esetén a Provi Domus Kft. 1-2 óra kiszállással dolgozik. A műemléki Wekerletelep épületeiben is tapasztaltak vagyunk. Munkadíj: 10.000–35.000 Ft.',
    'problema'   => 'A Wekerletelepem a régi épületek és az egyedi architektúra megkövetelik a tapasztalt, precíz munkát. A műemléki épületek sajátosságait ismerjük.',
    'testimonial_nev'    => 'Rácz Ferenc',
    'testimonial_szoveg' => 'Wekerletelepem régi házunkban kellett bojlert cserélni. Nehéz volt a hozzáférés, de megoldották. Precíz, rendezett munka.',
    'testimonial_ker'    => 'Budapest XIX. kerület – Wekerletelep',
    'faq_q'      => 'Vállalnak bojler cserét a XIX. kerületben, a Wekerletelepemen is?',
    'faq_a'      => 'Igen, a XIX. kerületben – Kispest, Wekerletelep – műemléki épületekben is dolgozunk. Kiszállás 1-2 óra, 0-24.',
    'szomszed'   => [10, 18, 20],
  ],

  20 => [
    'nev'        => 'XX. kerület',
    'roman'      => 'XX.',
    'reszek'     => 'Pesterzsébet, Gubacsipuszta, Török utca negyed',
    'jellemzo'   => 'A XX. kerület Pesterzsébet déli pesti lakónegyed – sok a régi téglaépület és panel. A bojlerek átlagkora magas, sok a csereérett készülék.',
    'hero_h1'    => 'Bojler Szerelő Budapest XX. Kerület – Pesterzsébet',
    'hero_sub'   => 'Villanybojler javítás, csere Pesterzsébeten – Gubacsipuszta, Török utca negyed. 1-2 óra kiszállás, 0-24.',
    'ai_text'    => 'A XX. kerületi – Pesterzsébet – bojler javítás esetén a Provi Domus Kft. 1-2 óra kiszállással dolgozik. Tégla és panel épületekben egyaránt tapasztaltak vagyunk. Munkadíj: 10.000–35.000 Ft.',
    'problema'   => 'Pesterzsébeten sok az elöregedett, 20+ éves bojler. Ha rozsdás vizet ad ki – azonnal cserélendő. Telefonon segítünk eldönteni.',
    'testimonial_nev'    => 'Simon Katalin',
    'testimonial_szoveg' => 'Pesterzsébeti lakásban rozsdás víz jött a bojlerből. Kiszálltak, megnézték – tartály korrodált, cserére ítélték. Új Ariston, másnap meleg víz.',
    'testimonial_ker'    => 'Budapest XX. kerület – Pesterzsébet',
    'faq_q'      => 'Rozsdás vizet ad a bojler a XX. kerületben – mit tegyek?',
    'faq_a'      => 'Ha rozsdás vizet ad a bojler, a tartály belülről korrodált – csere szükséges. Hívjon minket: a XX. kerületbe – Pesterzsébet – 1-2 óra alatt kiszállunk.',
    'szomszed'   => [9, 19, 23],
  ],

  21 => [
    'nev'        => 'XXI. kerület',
    'roman'      => 'XXI.',
    'reszek'     => 'Csepel, Csepeli lakótelep, Királyerdő, Csepel-North',
    'jellemzo'   => 'A XXI. kerület Csepel Budapest szigeten lévő városrész – a Csepeli lakótelep panelei és a sziget déli részének kertes házai eltérő igényeket mutatnak.',
    'hero_h1'    => 'Bojler Szerelő Budapest XXI. Kerület – Csepel',
    'hero_sub'   => 'Villanybojler javítás, csere Csepelen – Csepeli lakótelep, Királyerdő, Csepel-North. 1-2 óra kiszállás, 0-24.',
    'ai_text'    => 'A XXI. kerületi – Csepel – bojler javítás esetén a Provi Domus Kft. 1-2 óra kiszállással dolgozik. Panel és kertes ház bojlerjeit egyaránt kezeljük. Munkadíj: 10.000–35.000 Ft.',
    'problema'   => 'Csepelen a Duna víz magas mésztartalma felgyorsítja a bojler vízkövesedését. Évenkénti vízkőtelenítéssel érdemes megelőzni a komolyabb meghibásodást.',
    'testimonial_nev'    => 'Kocsis Péter',
    'testimonial_szoveg' => 'Csepeli panellakásban gyorsan meszesedik a bojler a dunai víz miatt. Évente hívom őket vízkőtelenítésre. Megbízhatóak, pontosak.',
    'testimonial_ker'    => 'Budapest XXI. kerület – Csepel',
    'faq_q'      => 'Miért meszesedik gyorsabban a bojler Csepelen?',
    'faq_a'      => 'A XXI. kerületben – Csepel – a Duna magas mésztartalmú vize felgyorsítja a vízkövesedést. Évente ajánlott a bojler vízkőtelenítése. Kiszállás 1-2 óra.',
    'szomszed'   => [9, 20, 22],
  ],

  22 => [
    'nev'        => 'XXII. kerület',
    'roman'      => 'XXII.',
    'reszek'     => 'Budatétény, Nagytétény, Budafok, Háros, Albertfalva',
    'jellemzo'   => 'A XXII. kerület Budapest déli budai oldala – Budafok borairól és Budatétény csendes utcáiról ismert. Sok a kertes ház és a kisebb társasház.',
    'hero_h1'    => 'Bojler Szerelő Budapest XXII. Kerület – Budafok, Budatétény, Nagytétény',
    'hero_sub'   => 'Villanybojler javítás, csere a XXII. kerületben – Budafok, Budatétény, Nagytétény, Háros. 1-2 óra kiszállás, 0-24.',
    'ai_text'    => 'A XXII. kerületi – Budafok, Budatétény – bojler javítás esetén a Provi Domus Kft. 1-2 óra kiszállással dolgozik. Kertes házak és kisebb társasházak bojlerjeit egyaránt kezeljük. Munkadíj: 10.000–35.000 Ft.',
    'problema'   => 'A XXII. kerületi kertes házakban Hajdú 100-150 literes bojlerek dominálnak. A nagy kapacitású készülékek karbantartása és cseréje is feladatunk.',
    'testimonial_nev'    => 'Németh Erzsébet',
    'testimonial_szoveg' => 'Budafokon, régi házunkban cseréltük a 15 éves Hajdút. Ketten jöttek, a nagy és nehéz bojlert kicserélték, a régit elvitték. Profi munka.',
    'testimonial_ker'    => 'Budapest XXII. kerület – Budafok',
    'faq_q'      => 'Vállalnak bojler cserét a XXII. kerületben, Budafokon és Budatétényen?',
    'faq_a'      => 'Igen, a XXII. kerületben – Budafok, Budatétény, Nagytétény – bojler cserét és javítást is vállalunk. Kiszállás 1-2 óra, 0-24.',
    'szomszed'   => [11, 21, 23],
  ],

  23 => [
    'nev'        => 'XXIII. kerület',
    'roman'      => 'XXIII.',
    'reszek'     => 'Soroksár, Újtelep, Soroksári lakótelep, Grassalkovich major',
    'jellemzo'   => 'A XXIII. kerület Budapest legdélebbi, legkisebb kerülete – Soroksár nyugodt, kertvárosi jellegű területe. A kertes házak és a lakótelep bojlerei egyaránt feladatot adnak.',
    'hero_h1'    => 'Bojler Szerelő Budapest XXIII. Kerület – Soroksár',
    'hero_sub'   => 'Villanybojler javítás, csere a XXIII. kerületben – Soroksár, Újtelep, Soroksári lakótelep. 1-2 óra kiszállás, 0-24.',
    'ai_text'    => 'A XXIII. kerületi – Soroksár – bojler javítás esetén a Provi Domus Kft. 1-2 óra kiszállással dolgozik. Budapest legdélebbi kerületébe is garantált a gyors kiszállás. Munkadíj: 10.000–35.000 Ft.',
    'problema'   => 'Soroksáron a kertes házak nagy részében idősebb, 15-20 éves bojlerek üzemelnek. A korai meghibásodás megelőzhető éves karbantartással.',
    'testimonial_nev'    => 'Takács Mihály',
    'testimonial_szoveg' => 'Soroksáron laktunk, mindenki azt mondta idáig nem jönnek. Provi Domus jött, megjavított. Nem kell félni a kerülettől. Köszönöm.',
    'testimonial_ker'    => 'Budapest XXIII. kerület – Soroksár',
    'faq_q'      => 'Vállalnak bojler javítást a XXIII. kerületben, Soroksáron?',
    'faq_a'      => 'Igen, a XXIII. kerületbe – Soroksár – is kiszállunk, 1-2 óra alatt. Budapest legdélebbi kerületét sem hagyjuk ki. 0-24.',
    'szomszed'   => [20, 22],
  ],

]; // $keruletek tömb vége

// Aktuális kerület adatai
$k = $keruletek[$kid];
$roman_szam = ['','I','II','III','IV','V','VI','VII','VIII','IX','X','XI','XII','XIII','XIV','XV','XVI','XVII','XVIII','XIX','XX','XXI','XXII','XXIII'];
